### ISSUE TITLE
[BUG] No detection 

### ISSUE THREAD

**Issue by ColterFranklin** [Mangonels/AntiXrayHeuristicsIssues#14]
**Server system:** Paper 1.16.4
**Minecraft version:** 1.16.4
**Steps to reproduce the issue:**  I purchased the plugin, installed it on my server with no issues and decided to test it with an alternate account. I managed to mine over a stack of diamonds within 30-45 minutes multiple times. No action was taken by the plugin.
**Error log:** N/A
**Link to config.yml file on gist.github.com:** I am using the default configuration file. The world in my server is named "world" so I left it as it is.

**Comment by Mangonels** [comment]
Hey,

Just to make sure, you wouldn't have been under any of these factors?:
- Mining in creative mode first, or with extremely OP tools, which would allow you to confuse AXH, with the same account, before mining with more normal circumstances, both using xrays. (Still I doubt this since you claim to have been doing 15min sessions for an entire day if I'm correct? That would be enough for AXH to get it together.)
- Your ore and terrain generation for the monitored world/s are very close to, or 100% vanilla. Else, the plugin's configuration will do it's best to provide with options in order to calibrate itself according to your own ore scarcity. However, there is no guarantee the plugin will work as intended if your generation is not Vanilla.

Also, did you xray normally or did you stall for time?

Try lifting some weights for emerald, diamond and netherite, it's very strange that you wouldn't get detected after mining for so long, IF you presented obvious xray usage. If you're not getting detected at all, then lifting the weights should be harmless.

**Comment by ColterFranklin** [comment]
Hey, I appreciate the quick reply and depth :)

1) I used a clean alt account to perform my testing. The account has never had admin permissions or OP tools.
2) The terrain generation is completely vanilla.

As for the way in which I xrayed, as soon as I logged in I begun mining directly towards diamonds. I very rarely stalled and was mining diamonds aggressively. 

Something to note though, I am using the default configuration, but do I need to add "overworld" to my list of worlds, as well as "world" and "world_nether"?

I have setup a clean test server and am going to try again. 

Cheers

**Comment by Mangonels** [comment]
> Something to note though, I am using the default configuration, but do I need to add "overworld" to my list of worlds, as well as "world" and "world_nether"?

You only need to add the exact world names where you want AXH to track.

**Comment by ColterFranklin** [comment]
It worked on the test server finally after I mined after 54 diamonds. 

Must be very dependant on the circumstances/behavior

Thank you

**Comment by Mangonels** [comment]
> It worked on the test server finally after I mined after 54 diamonds.
> 
> Must be very dependant on the circumstances/behavior
> 
> Thank you

Yeah, still, I suspect the default weights can be pushed higher without any issues. They're only that low because I haven't been able to confirm this.

**Comment by ColterFranklin** [comment]
Hey there, 

I have put the weight of diamonds up to 20 from default and still don't get detected until i've mined over a stack.

Do you know how much can I increase the weight before it becomes an issue for legitimate players? It would be ideal if they were handled after mining like 20 or 30 diamonds, similar to the example video.

Thanks
