### ISSUE TITLE
[HELP] Question

### ISSUE THREAD

**Issue by strahil211** [Mangonels/AntiXrayHeuristicsIssues#15]
**Server system:** Paper
**Minecraft version:** 1.16.5

I was X-raying on my alt (not op) and it did not detect me. Is there a way to tighten up the config to make it actually stop me from X-raying more than 15 diamonds?

**Comment by strahil211** [comment]
Why is it taking so long to get a response?

**Comment by Mangonels** [comment]
> **Server system:** Paper
> **Minecraft version:** 1.16.5
> 
> Is there a way to tighten up the config to make it actually stop me from X-raying more than 15 diamonds?

Right now there probably isn't (at least not with diamonds). If you haven't done it already, you can try increasing the weights ever so slightly, until you start getting false positives. I am working on providing some better default weights.

The system is designed to make sure that the players detected are **really** using xrays. I designed it so that the speed at which it does this isn't really consequential (although it detects fairly quickly when you're mining ancient debris), but rather the fact that most xrayers will bump into this threshold, and the economy won't be ruined thanks to it.

I hope this answers your question, if you have any more, please reopen, I've been busy these last days, that's why I didn't answer inmediately (I often do, so don't judge me on this one).
