### ISSUE TITLE
[BUG] API issues

### ISSUE THREAD

**Issue by RidaThe94** [Mangonels/AntiXrayHeuristicsIssues#19]
**Server system:** [Spigot/Paper] Paper
**Minecraft version:**  1.16.5
**Steps to reproduce the issue:** I have made a plugin that announce violations of AXH and it broke on 1.3.8 but still works on 1.3.7 because of changes in MiningSession Class.
https://pastebin.com/tyHsxEkb

**Comment by RidaThe94** [comment]
in es.mithrandircraft.antixrayheuristics.AntiXrayHeuristics
change
```
    protected HashMap<String, MiningSession> sessions;
```
to
    public HashMap<String, MiningSession> sessions;
```

and in es.mithrandircraft.antixrayheuristics.MiningSession
change 
```
class MiningSession
```
to
```
public class MiningSession
```

**Comment by Mangonels** [comment]
This would indeed fix the issue for you, but the point of having an API is to make propper software interconnectivity.

You mentioned you intend to make a violation announcement plugin. Depending on what you wish to do, the right way of doing it would be to listen to the api's HandlingXrayerEvent. If this event is not enough for you, please state what else you wish to access, and I'll add it. If it doesn't work, please state exactly what doesn't work.

In any case the issue here is with the api, and I don't feel like just mindlessly implementing classes fields and methods as public is the propper way to solve this.

**Comment by RidaThe94** [comment]
I have tried HandlingXrayerEvent and its not the same as I am trying to get the suspicion level of that player and I couldn't find other way to get it other than the MiningSession Class, maybe you don't have to make it public, but make a way to access it via the API so I can get the suspicion level from it.

**Comment by Mangonels** [comment]
> I have tried HandlingXrayerEvent and its not the same as I am trying to get the suspicion level of that player and I couldn't find other way to get it other than the MiningSession Class, maybe you don't have to make it public, but make a way to access it via the API so I can get the suspicion level from it.

May I ask why you need the suspicion level? I'm not very confortable with letting it be easily visible, even at a programming level, for reasons I've stated many times. Here's one of them: https://github.com/Mangonels/AntiXrayHeuristicsIssues/issues/12

If it's fine with you, I'm going to make the notifications myself, as part of AXH. If you have any input/specifications on how you'd like this to work (aproximately), please let me know. Maybe that would remove the need for you to access this data, which I consider sensitive.

**Comment by RidaThe94** [comment]
> > I have tried HandlingXrayerEvent and its not the same as I am trying to get the suspicion level of that player and I couldn't find other way to get it other than the MiningSession Class, maybe you don't have to make it public, but make a way to access it via the API so I can get the suspicion level from it.
> 
> May I ask why you need the suspicion level (maybe in what way you use it for your violations announcer)? I'm not very confortable with letting it be easily visible, even at a programming level, for reasons I've stated many times. Here's one of them: #12
> 
> If it's fine with you, I'm going to make the notifications myself, as part of AXH. If you have any input/specifications on how you'd like this to work (aproximately), please let me know. Maybe that would remove the need for you to access this data, which I consider sensitive.

I have responded to you in spigot pms regarding how I use it for announcements. I will bump the message there just in case since I didn't get a response there.

**Comment by Mangonels** [comment]
Yes, I read it. However, it's kinda hard to understand you, and you did not need to pm me. Answering this ticket would have been perfectly fine.

Also, I do not consider the notification system priority right now. But it will be implemented eventually. I am sorry that you find yourself in this situation, and apollogize for having technically "reduced the plugin's functionality/usefulness".

For now I think I am going to close this ticket since it is not really clear if the API has any actual issues (which was the original topic of this ticket) in what it's meant to do.

Feel free to open another ticket making a detailed suggestion on how you'd like to see the planned notification system. Please do not copy paste the contents of your PM response, for I consider it could be better formatted as a suggestion.
