### ISSUE TITLE
[BUG] No detection

### ISSUE THREAD

**Issue by russianpeanut** [Mangonels/AntiXrayHeuristicsIssues#29]
Server system: Paper
Minecraft version: 1.16.5
Steps to reproduce the issue: i have deop and i am xraying and it doesnt punish me it ignores me i setuped the worlds correctly
Error log: no errors
Link to config.yml file on gist.github.com: https://gist.github.com/russianpeanut/e5a19c64f589d00a8b66b0a1333dea58

**Comment by Mangonels** [comment]
Please detail how long you xrayed for, and what ores you obtained from xraying.

Also confirm that you are using a Vanilla terrain generation, and no mining tools with efficiency above V

**Comment by russianpeanut** [comment]
i have xrayed for like 4 mins, i mined diamonds and gold.
 
 No, i use plugin named realistic world generator and normal efficiency V

**Comment by russianpeanut** [comment]
Realistic World Generator doesnt change the ore spawning or cave system i think

**Comment by Mangonels** [comment]
Your generator doesn't need to change the ore spawning and cave system in order to make AXH's core algorithm impredictable. 

I believe your terrain generation is the issue.

![image](https://user-images.githubusercontent.com/24245302/128605711-5b7d7712-793c-4a31-b57b-72ef3127c586.png)

However, future versions of AXH may help with these cases. I already commented I'll work on a new system that accounts for any kind of terrain, but I can't promise it will actually work perfectly. I'll always prioritize AXH working perfectly with vanilla generations, so the core algorithm will always prioritize that working properly over other generations.

**Comment by russianpeanut** [comment]
So i need to wait until you make option for custom generation?

**Comment by Mangonels** [comment]
> So i need to wait until you make option for custom generation?

Waiting is your best option right now, or switching to a more resource intensive anti-xraying approach.

In any case, it's pretty much settled that the feature I mentioned will be part of following releases, since it's also necessary for cross-version compatibility, and specially compatibility with newer 1.17 and 1.18 versions, which completely revamp the whole subterraneal structure of the game.
